### ISSUE TITLE
No EnrcyptSettings Method

### ISSUE THREAD

**Issue by Master-Silver** [ChustaSoft/SecureConfig#32]
What did i miss?

![NoEncrypt](https://user-images.githubusercontent.com/26323699/92239906-08601b80-eebc-11ea-836e-72231e056176.png)

![Packages](https://user-images.githubusercontent.com/26323699/92240057-49f0c680-eebc-11ea-8375-93322db4cff7.png)

**Comment by xaberue** [comment]
Hi @Master-Silver !!

First of all thank you for asking and for using SecureConfig tool.

It is a ASP .NET Core 3.1 app??, if that is the case, the issue could be that CreateWebHostBuilder is giving you a IWebHostBuilder interface, and that is not the appropiate from .NET Core 3.1

Could you please check this?

I will provide a full example:
`Host.CreateDefaultBuilder(args)`
`    .ConfigureWebHostDefaults(webBuilder =>`
`    {`
`        webBuilder.UseStartup<Startup>();`
`    })`
`    .Build()`
`    .EncryptSettings<AppSettings>(true)`
`    .Run();`

**Comment by Master-Silver** [comment]
@Xelit3 yes it is now are .NET Core 3.1 app, previously is was are NET Core 2.1 app, so the may some old code in it. I will check your example next monday, but thanks for the quick response.

![HostBuild](https://user-images.githubusercontent.com/26323699/92247898-292e6e00-eec8-11ea-8319-b281eed32728.png)

**Comment by xaberue** [comment]
Perfect!

.Net Core 2.x had a different way to build Host, through IWebHostBuilder, SecureConfig has this for .NET Core 2.x versions, however for .NET Core 3.1 is done through IHostBuilder, SecureConfig is only providing the appropiate EncryptSettings method for any version.

You can take a look at [this example](https://github.com/ChustaSoft/SecureConfig/blob/master/ChustaSoft.Tools.SecureConfig.NetCore3.TestApi/Program.cs) available in our repo for .NET Core 3.x applications

Thank you again for asking @Master-Silver,  I hope this helps you

**Comment by Master-Silver** [comment]
The call of EncryptSettings is now fine, but i did get a new problem in the startup. My class UniFiSettings exist and the field Configuration is not null, so I'm a little clueless about this. I did also download the NET Core 3.1 example from you and it ran without a problem.

![Screenshot_2020-09-07 Internal Server Error](https://user-images.githubusercontent.com/26323699/92374823-9298c180-f100-11ea-84a6-0625f2c7b9da.png)

**Comment by Xelit3** [comment]
Hi again @Master-Silver , 

I can see that you are encripting a class called AppSettings, but then you are trying to manage another one, should be the same.

This could be the problem

**Comment by xaberue** [comment]
Hi @Master-Silver ,

Can I see the name of the parameter that you are using for such setting class in appSettings file?

**Comment by Master-Silver** [comment]
Hi Xelit3
I did change that to this class. 

![Setting_Class](https://user-images.githubusercontent.com/26323699/92377037-cde8bf80-f103-11ea-8510-1388475e5920.png)
![AppSettings](https://user-images.githubusercontent.com/26323699/92377043-cfb28300-f103-11ea-9f73-2af7ab073049.png)

**Comment by xaberue** [comment]
Good point, by the moment, internallly the project can handle different settings name from appSettings, unfortunately, the extension mehod for the configuration is not allowing to specify something specific, so you are restricted to use "AppSettings" name

Let me check if I can apply an enhacenment here quickly, which seems easy, and from which I will open new issue

**Comment by Master-Silver** [comment]
Ah I see, now this make sense to me. Didn't know that the class name was fixed.

**Comment by xaberue** [comment]
By the way, I will publish now another version, no breaking change, with that, you will have two options:
1. Just name AppSettings at appSettings file, this will work with the current version and the new one
2. Be able to provide a custom name for the appSetttings section, this will be allowed from the version that I am going to publish

If you want to apply the change of the new version, you will require first to have the file decrypted. You already have this option using: EncryptSettings(false), it will decrypt for you

I will keep yoo posted [here ](https://github.com/ChustaSoft/SecureConfig/issues/33)and inside [release notes](https://github.com/ChustaSoft/SecureConfig/wiki/Release-notes)

**Comment by xaberue** [comment]
Hi @Master-Silver 

Version 1.2.2 is published, just let me know if at the end you are going to use the default implementation or the custom one, everything is already documented, however if you need help I will be glad to help you

Best regards :)
