### ISSUE TITLE
Allow to use custom AppSetting's param name for appSettings section

### ISSUE THREAD

**Issue by xaberue** [ChustaSoft/SecureConfig#33]
Currently, the project only allows to encrypt and decrypt sections whose name is "AppSettings", 

Allowing the name to be flexible can give more configuration flexibility to the client project

**Comment by Master-Silver** [comment]
Hi @Xelit3 
I tried this out and there was some unwanted behavior. The settings are correctly read but the encrypted value is not written in the same key and so does not overwrite the plane values. It will build a new Appsettings key on the end of the file and write in there. If it's decrypting it will write the values there as well.

![SetUpCall](https://user-images.githubusercontent.com/26323699/92382560-148ee780-f10d-11ea-957d-62f16aca07c1.png)

![AppSettings](https://user-images.githubusercontent.com/26323699/92382546-1062ca00-f10d-11ea-9e89-e2ef38afffb3.png)

**Comment by xaberue** [comment]
Hi @Master-Silver 

Could you check if you have done the same in EncryptSettings:
`.EncryptSettings(true, "UniFiSettings")`

You could check this [here](https://github.com/ChustaSoft/SecureConfig/wiki#deep-configuration), also inside the [release notes](https://github.com/ChustaSoft/SecureConfig/wiki/Release-notes)

Best regards

**Comment by Master-Silver** [comment]
Hi @Xelit3 

you are right, I missed that, sorry.

Thanks for your time

**Comment by xaberue** [comment]
Np @Master-Silver ! It is working now?

**Comment by Master-Silver** [comment]
Yes it works now.
